"""Ersetzt den B3-Monat in buch/zeitleiste.json durch den neuen Stand."""
import json

with open('buch/zeitleiste.json', 'r', encoding='utf-8') as f:
    z = json.load(f)

neu = {
    "label": "Buch 3 — MZ Monat 5 bis 10",
    "mz": "3635 MZ Monat 5 bis 10",
    "tz": "1987 bis 2155 TZ",
    "events": {
        "thalassien": [
            {"tz": "~1990", "mz": "Monat 5,5", "titel": "I7 Maren gründet die Schwellenforschungsgesellschaft in Vael",
             "detail": "Werft-Erbe als Sitz, drei Mitglieder, Karte des Steinkreises an der Wand.",
             "typen": ["schlüssel"], "tags": ["Institut-Gründung"]},
            {"tz": "~2019", "mz": "Monat 6 (Akt II früh)", "titel": "I13 Tyra Halvard + Forschungs-Expedition vor Aufbruch",
             "detail": "Team 15 Personen, Tyra verabschiedet ihre Schwester. Portal öffnet sich, sie treten durch.",
             "typen": ["begegnung", "tschechow"], "tags": ["Expedition 1"]},
            {"tz": "~2037", "mz": "Monat 6,5 (Akt II spät)", "titel": "I8 Verwüster-Angriff auf Vael — Maren stirbt",
             "detail": "Drei Orath-Rufer-Schemen durch Varens geöffnetes Portal. Institut-Außengebäude zerstört, ~40 Tote. Marens letzte Worte: \u201eIch habe sie hergeschickt.\u201c",
             "typen": ["tod", "schlüssel"], "tags": ["Marens Tod", "Wendepunkt"]},
            {"tz": "~2080", "mz": "Monat 7,8 (Akt III)", "titel": "I9 Institut-Wandel — junge Halvard trifft jungen Velkan",
             "detail": "Dr. Syra Halvard (15, Stipendiatin) und Kelvar Velkan (25, Sicherheitsoffizier) lernen sich kennen. Eroberungs-Doktrin wächst.",
             "typen": ["begegnung"], "tags": ["Institut-Wandel"]},
            {"tz": "~2110", "mz": "Monat 8,7 (Akt III spät)", "titel": "I14 Halvard + Velkan planen Expedition 2",
             "detail": "Resonanz-Modulator im Test, 2500 Soldaten in Vorbereitung. 72-Stunden-Portal. Kein Purpurstein, reine 2110er-Tech.",
             "typen": ["schlüssel"], "tags": ["Expedition 2 Planung"]},
            {"tz": "~2120", "mz": "Monat 9 (Akt IV früh)", "titel": "I16 Expedition 2 bricht auf",
             "detail": "2500 Soldaten + Drohnen + Exoskelette + Biotech treten durchs Portal. Velkan führt. Modulator schmilzt nach 72 Stunden.",
             "typen": ["portal", "schlüssel"], "tags": ["Expedition 2 Aufbruch"]},
            {"tz": "~2155", "mz": "nach Portal-Schluss (Akt IV/Epilog)", "titel": "I15 Thalassien magielos — Kind berührt Farn",
             "detail": "Farn bewegt sich nicht. Keine Resonanz mehr. Institutsfassade mit Marens Name in Stein. Stille unter dem Botanischen Garten.",
             "typen": ["schlüssel"], "tags": ["Thalassien-Ende"]}
        ],
        "moragh": [
            {"tz": "~2003", "mz": "Monat 5,5 (Akt I)", "titel": "Alphina + Varen in Torkal — erste Quellen-Reparatur (Halvara-Kel)",
             "detail": "Alphinas Puls injiziert, Quelle pocht kurz. Hält nur Tage. Varen verschweigt die energetische Unmöglichkeit.",
             "typen": ["tschechow"], "tags": ["Hoffnungs-Betrug"]},
            {"tz": "~2003", "mz": "Monat 5,5", "titel": "Vesper + Nyr bei Thar, sehen Expedition kommen",
             "detail": "Vesper rechnet den Tech-Gradienten hoch, warnt Thar-Kommandantin. Sie hört halb zu.",
             "typen": ["erkenntnis"], "tags": []},
            {"tz": "~2003", "mz": "Monat 5,5", "titel": "Runa in Halvaren — druckt zweisprachige Flugblätter",
             "detail": "Wartet innerlich, Bund-Loyalität brüchig nach Sulkara.", "typen": ["hintergrund"], "tags": []},
            {"tz": "~2020", "mz": "Monat 6 (Akt I)", "titel": "Erste Expedition (Forschung) kommt in Moragh an",
             "detail": "15 Wissenschaftler, Tyra Halvard als Linguistin. Thar empfängt vereinnahmend.",
             "typen": ["begegnung"], "tags": ["Expedition 1 Ankunft"]},
            {"tz": "~2037", "mz": "Monat 6,5 (Akt II)", "titel": "Erste Expedition scheitert blutig",
             "detail": "11 tot, 2 verschwunden, 2 fliehen. Nur Tyra kommt später bis zur Gruppe.",
             "typen": ["tod"], "tags": []},
            {"tz": "~2037", "mz": "Monat 6,5", "titel": "Varen manipuliert Orath-Älteste zur Verwüster-Beschwörung",
             "detail": "Orather Rufer beschwören drei Verwüster-Schemen. Varen öffnet Portal zurück nach Vael.",
             "typen": ["schlüssel"], "tags": []},
            {"tz": "~2047", "mz": "Monat 6,8", "titel": "Iven (17, Elektrizitäts-Resonanz) wird in Moragh entdeckt",
             "detail": "Berührt Thalassien-Generator — Leistung verdoppelt sich. Zahlt mit dem Körper.",
             "typen": ["begegnung", "tschechow"], "tags": []},
            {"tz": "~2054", "mz": "Monat 7", "titel": "Alphina versucht Runa in Halvaren zu überzeugen",
             "detail": "Drei-Sätze-Absage: \u201eDu riechst nach ihm. Du sprichst wie er. Ich glaube dir nicht.\u201c",
             "typen": ["begegnung", "erkenntnis"], "tags": []},
            {"tz": "~2062", "mz": "Monat 7,2", "titel": "Elke ermordet (aufgeladener Schemen, Varen-Auftrag)",
             "detail": "In der Küche, Leiche im Garten platziert. Basalt-Splitter fehlt. Alphina verdächtigt Talven.",
             "typen": ["tod", "schlüssel"], "tags": ["Elkes Mord"]},
            {"tz": "~2062", "mz": "Monat 7,2", "titel": "Varen pflanzt gefälschte Beweise gegen Talven",
             "detail": "Notizzettel, Schemen-Splitter, Lied-Gerücht. Alle drei Indizien zeigen scheinbar auf Talven.",
             "typen": ["tschechow"], "tags": []},
            {"tz": "~2062", "mz": "Monat 7,2", "titel": "Talven beginnt mit Blutmagie + Schemen-Binden",
             "detail": "Varen spielt ihm die Velmar-Bindetechnik zu. Talven radikalisiert sich unter Alphinas Verdacht.",
             "typen": ["tschechow"], "tags": []},
            {"tz": "~2087", "mz": "Monat 8", "titel": "Alphina findet das Ritual-Dokument in Varens Quartier",
             "detail": "Vier-Thalassier-Liste, eigener Name als Rechengröße. Der Satz über Sorel. Sie verlässt Varen ohne Drama.",
             "typen": ["erkenntnis", "schlüssel"], "tags": ["Bruch mit Varen"]},
            {"tz": "~2095", "mz": "Monat 8,3", "titel": "Runa läuft aus dem Bund über",
             "detail": "Drael-Lügen über die Expedition-Gefährdung werden zu viel. Runa flieht in eine freie Stadt.",
             "typen": ["schlüssel"], "tags": []},
            {"tz": "~2103", "mz": "Monat 8,5", "titel": "Wiederbegegnung Alphina + Runa",
             "detail": "Alphina weint. Runa versteht, verzeiht — darf aber wütend sein. Ruhige harte Anerkennung.",
             "typen": ["begegnung", "erkenntnis"], "tags": []},
            {"tz": "~2103", "mz": "Monat 8,5", "titel": "Nyr verlässt die Thar",
             "detail": "Zivilisten-als-Schild-Befehle. Verabschiedet sich von Vesper, bietet Beistand an.",
             "typen": ["schlüssel"], "tags": []},
            {"tz": "~2112", "mz": "Monat 8,7", "titel": "Alphina tötet Talven (Fehlurteil)",
             "detail": "Konfrontation allein. Blutmagie + Schemen-Schwarm gegen Dornen. Er bestreitet Elkes Mord bis zuletzt. Letzter Satz: \u201eIch hätte es irgendwann wirklich gekonnt.\u201c",
             "typen": ["tod", "schlüssel"], "tags": ["Zweite Schuld"]},
            {"tz": "~2120", "mz": "Monat 9 (Akt III/IV)", "titel": "Zweite Expedition überrennt Dravek",
             "detail": "2500 Soldaten, Exoskelette, Drohnen. Basislager am Steinplatz, sichert Portal. Kein aktives Erobern umliegender Städte.",
             "typen": ["schlüssel"], "tags": ["Expedition 2 Ankunft"]},
            {"tz": "~2120", "mz": "Monat 9", "titel": "Notbündnis Orath + Thar",
             "detail": "Strategische Bedrohung durch mögliche zweite Welle. Drael + Thar-Kommandantin treffen sich. Vesper wird Stratege.",
             "typen": ["schlüssel"], "tags": []},
            {"tz": "~2128", "mz": "Monat 9,3 (Akt IV)", "titel": "Varen versammelt seinen Zirkel (20–30 Anhänger)",
             "detail": "Handverlesen über Jahre. Sie glauben an die Wiedergutmachungs-Geschichte.",
             "typen": ["hintergrund"], "tags": []},
            {"tz": "~2136", "mz": "Monat 9,5", "titel": "Schlacht beginnt — Bündnis gegen Expedition bei Dravek",
             "detail": "Orath-Rufer, Thar-Bestien-Reiter, Varen-Abtrünnige, freie Städte-Kämpfer. Iven lahmt Expeditions-Elektronik.",
             "typen": ["kampf"], "tags": []},
            {"tz": "~2144", "mz": "Monat 9,7", "titel": "Duell Varen vs. Alphina + Vesper",
             "detail": "Vesper verliert linken Unterarm (Bindungsmagie durch aufgeladenen Schemen). Alphina verliert drei Finger (Mittel-, Ring-, kleiner bis Mittelglied). Reveal-Sequenz Varen: \u201eKleine naive Alphina\u201c \u2192 \u201eDu warst sauberer zu lesen als Sorel\u201c \u2192 \u201eNur deinen Frequenzwert\u201c \u2192 \u201eSie starb in der Küche\u201c \u2192 \u201eGarten.\u201c Alphina gibt Todesstoß.",
             "typen": ["tod", "schlüssel", "kampf"], "tags": ["Varens Tod", "Reveal"]},
            {"tz": "~2152", "mz": "Monat 9,9", "titel": "Verzweiflungsangriff auf Expedition-Basislager Dravek",
             "detail": "Expedition reaktiviert Modulator. Zweite Durchgangs-Welle beginnt — stockwerkshohe Killermaschinen, Gigant-Drohnen. Tausende Moragh-Tote auf dem Weg zur Portal-Quelle.",
             "typen": ["kampf"], "tags": []},
            {"tz": "~2153", "mz": "Monat 10", "titel": "Alphina überlädt Portal-Quelle — Portal tot für immer",
             "detail": "Solo-Akt. Wachstums-Überladung (Pflanzen-Spur, Stufe 10). Quelle kollabiert in beiden Welten gleichzeitig. Eine halbdurchgetretene Killermaschine wird gekappt.",
             "typen": ["portal", "schlüssel"], "tags": ["Portal-Schluss"]},
            {"tz": "~2153", "mz": "Monat 10", "titel": "Thalassien verliert alle Magie permanent",
             "detail": "Raumzeit-Risse schließen sich. Farne still, warme Steine kühlen. Die 5 Thalassier in Moragh behalten ihre Resonanz.",
             "typen": ["schlüssel"], "tags": []},
            {"tz": "~2153", "mz": "Monat 10", "titel": "Kessler mitgenommen, Vesper-Unterarm amputiert",
             "detail": "Reiter-Bindung absolut. Nyr reitet Kessler nach Halvek-Mar. Runa repariert unterwegs mit Feuer. Vesper-Amputation unterhalb des Ellbogens.",
             "typen": ["hintergrund"], "tags": []},
            {"tz": "~2155", "mz": "Epilog", "titel": "Vier in Halvek-Mar — Alphina, Vesper, Runa, Nyr",
             "detail": "Am Tisch. Tyra Halvard in der Nähe. Runa: \u201eIch hatte recht. Und ich hätte dich trotzdem mitgenommen.\u201c Alphina: \u201eIch weiß.\u201c Meer, Stille.",
             "typen": ["begegnung", "schlüssel"], "tags": ["Epilog"]},
            {"tz": "~2155", "mz": "Epilog", "titel": "Expedition-Überlebende brechen in tote Zonen aus",
             "detail": "~1500 Gestrandete ziehen aus Dravek nach Süd-Ost in die toten Zonen Mar-Keth, Dulrath-Ost, Reshkol. Keimzelle einer anti-magischen Fraktion. Fluggeräte erkunden den Planeten.",
             "typen": ["hintergrund", "schlüssel"], "tags": ["B4-Setup"]}
        ]
    }
}

z['monate'][20] = neu

with open('buch/zeitleiste.json', 'w', encoding='utf-8') as f:
    json.dump(z, f, ensure_ascii=False, indent=2)

print(f"B3-Monat ersetzt. Thalassien: {len(neu['events']['thalassien'])} Events, Moragh: {len(neu['events']['moragh'])} Events.")
